# Generated by Django 5.2.4 on 2025-07-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_id', models.CharField(max_length=50)),
                ('tip_desc', models.CharField(max_length=500)),
                ('tip_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
