# Generated by Django 5.2.4 on 2025-07-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userplant',
        ),
    ]
