# Generated by Django 5.2.4 on 2025-07-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='tip_name',
            field=models.CharField(default='Untitled', max_length=100),
            preserve_default=False,
        ),
    ]
