# Generated by Django 5.2.4 on 2025-07-13 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_delete_userplant'),
    ]

    operations = [
        migrations.CreateModel(
            name='userplant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('plant_type', models.CharField(blank=True, choices=[('Succulent', 'Succulent'), ('Fern', 'Fern'), ('Cactus', 'Cactus'), ('Herb', 'Herb'), ('Other', 'Other')], max_length=50)),
                ('custom_image', models.ImageField(blank=True, null=True, upload_to='user_plants/')),
                ('location', models.CharField(blank=True, choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=10)),
                ('sunlight', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('humidity', models.CharField(blank=True, max_length=100)),
                ('planted_date', models.DateField(default=datetime.date.today)),
                ('last_watered', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('watering_frequency', models.PositiveIntegerField(blank=True, help_text='In days', null=True)),
                ('current_status', models.CharField(choices=[('Healthy', 'Healthy'), ('Needs Attention', 'Needs Attention'), ('Dying', 'Dying'), ('Dead', 'Dead')], default='Healthy', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
