# Generated by Django 5.2.4 on 2025-07-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_tips_tip_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='plantinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plant_name', models.CharField(max_length=50)),
                ('Scientific_name', models.CharField(max_length=100)),
                ('Light_requirement', models.CharField(max_length=500)),
                ('Watering_frequency', models.CharField(max_length=500)),
                ('Soil_type', models.CharField(max_length=500)),
                ('Temperature_range', models.CharField(max_length=500)),
                ('Humidity_preference', models.CharField(max_length=500)),
                ('Fertilizer_info', models.CharField(max_length=500)),
                ('Pruning_tips', models.CharField(max_length=500)),
                ('Growth_pattern', models.CharField(max_length=500)),
                ('Toxicity_info', models.CharField(max_length=500)),
                ('Care_difficulty', models.CharField(max_length=500)),
                ('Plant_img', models.ImageField(upload_to='plant_images/')),
            ],
        ),
    ]
