# Generated by Django 5.2.4 on 2025-07-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_plantinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantinfo',
            old_name='Plant_img',
            new_name='plant_img',
        ),
        migrations.RenameField(
            model_name='plantinfo',
            old_name='Plant_name',
            new_name='plant_name',
        ),
        migrations.RemoveField(
            model_name='plantinfo',
            name='Care_difficulty',
        ),
        migrations.RemoveField(
            model_name='plantinfo',
            name='Fertilizer_info',
        ),
        migrations.RemoveField(
            model_name='plantinfo',
            name='Growth_pattern',
        ),
        migrations.RemoveField(
            model_name='plantinfo',
            name='Humidity_preference',
        ),
        migrations.RemoveField(
            model_name='plantinfo',
            name='Light_requirement',
        ),
        migrations.RemoveField(
            model_name='plantinfo',
            name='Pruning_tips',
        ),
        migrations.RemoveField(
            model_name='plantinfo',
            name='Scientific_name',
        ),
        migrations.RemoveField(
            model_name='plantinfo',
            name='Soil_type',
        ),
        migrations.RemoveField(
            model_name='plantinfo',
            name='Temperature_range',
        ),
        migrations.RemoveField(
            model_name='plantinfo',
            name='Toxicity_info',
        ),
        migrations.RemoveField(
            model_name='plantinfo',
            name='Watering_frequency',
        ),
        migrations.AddField(
            model_name='plantinfo',
            name='plant_desc',
            field=models.CharField(default='untitled', max_length=50000),
            preserve_default=False,
        ),
    ]
