# Generated by Django 5.2.4 on 2025-07-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_rename_plant_img_plantinfo_plant_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantinfo',
            name='plant_desc',
            field=models.TextField(max_length=50000),
        ),
    ]
