# Generated by Django 5.2.4 on 2025-07-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_alter_userplant_plant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplant',
            name='plant_type',
            field=models.CharField(blank=True, choices=[('Succulent', 'Succulent'), ('Fern', 'Fern'), ('Cactus', 'Cactus'), ('Herb', 'Herb'), ('Other', 'Other')], max_length=50),
        ),
    ]
