# Generated by Django 5.2.4 on 2025-07-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_alter_plantinfo_plant_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantinfo',
            name='plant_id',
            field=models.CharField(default='untitled', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
