# Generated by Django 5.2.4 on 2025-07-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_alter_userplant_plant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='fertilizing_frequency',
            field=models.PositiveIntegerField(blank=True, help_text='In days', null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='is_flowering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userplant',
            name='is_fruiting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userplant',
            name='last_fertilized',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userplant',
            name='temperature_preference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userplant',
            name='water_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='last_watered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
