# Generated by Django 5.2.4 on 2025-07-13 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_userplant_fertilizing_frequency_userplant_height_cm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplant',
            old_name='sunlight',
            new_name='sunlight_available',
        ),
        migrations.AlterField(
            model_name='userplant',
            name='fertilizing_frequency',
            field=models.PositiveIntegerField(blank=True, help_text='How often to fertilize, in days.', null=True),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='humidity',
            field=models.CharField(blank=True, help_text='humidity level (e.g., “High humidity”)', max_length=100),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='is_flowering',
            field=models.BooleanField(default=False, help_text='whether the plant is currently flowering.'),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='is_fruiting',
            field=models.BooleanField(default=False, help_text='whether the plant is producing fruit.'),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='last_fertilized',
            field=models.DateField(blank=True, help_text='Date when the plant was last given fertilizer.', null=True),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional notes – observations, reminders, or tips.'),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='planted_date',
            field=models.DateField(default=datetime.date.today, help_text='The date when the plant was planted'),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='source',
            field=models.CharField(blank=True, help_text='Where the plant came from (e.g., "Local Nursery", "Gift", "Online").', max_length=100),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='temperature_preference',
            field=models.CharField(blank=True, help_text='Ideal temperature range or preference (e.g., “15–25°C”).', max_length=100),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='watering_frequency',
            field=models.PositiveIntegerField(blank=True, help_text='How often the plant should be watered, in days (e.g., every 3 days).', null=True),
        ),
    ]
