# Generated by Django 5.2.4 on 2025-07-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_plantinfo_plant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantinfo',
            name='plant_id',
            field=models.CharField(max_length=50),
        ),
    ]
