# Generated by Django 5.2.4 on 2025-07-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_alter_plantinfo_plant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='plantinfo',
            name='plant_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
