# Generated by Django 5.2.4 on 2025-07-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userprofile',
        ),
    ]
