# Generated by Django 5.2.4 on 2025-07-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0014_userplant_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
