# Generated by Django 5.2.4 on 2025-07-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0015_userplant_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplant',
            old_name='is_flowering',
            new_name='is_flowering_and_fruiting',
        ),
        migrations.RemoveField(
            model_name='userplant',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='userplant',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='userplant',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='userplant',
            name='is_fruiting',
        ),
        migrations.RemoveField(
            model_name='userplant',
            name='source',
        ),
        migrations.RemoveField(
            model_name='userplant',
            name='temperature_preference',
        ),
        migrations.RemoveField(
            model_name='userplant',
            name='water_reminder',
        ),
    ]
